# Generated by Django 3.1 on 2021-09-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
